/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Graph graph = new Graph();

        graph.addVertex("Mocha");
        graph.addVertex("Lio");
        graph.addVertex("Bondo2");
        graph.addVertex("Dongol");

        graph.addEdge("Mocha", "Lio");
        graph.addEdge("Bondo2", "Lio");
        graph.addEdge("Dongol", "Lio");
        graph.addEdge("Bondo2", "Dongol");
        graph.addEdge("Dongol", "Mocha");


        System.out.println("the graph => " + graph.printGraph());
        System.out.println("the size => " + graph.size());
        System.out.println();
        System.out.println(graph.getNeighbors("Lio"));

        System.out.println();

        graph.removeEdge("Mocha","Lio");
        System.out.println("After delete Edge => "+ graph.printGraph());

        System.out.println();
        System.out.println();
        graph.removeVertex("Dongol");
        System.out.println("After delete Vertex => "+ graph.printGraph());

        System.out.println();
        System.out.println();
        System.out.println(graph.getVertices());
        System.out.println();
        System.out.println();
        System.out.println(graph.getNeighbors("Lio"));

        Graph graph1 = new Graph();

        graph1.addVertex("Pandora");
        graph1.addVertex("Arendelle");
        graph1.addVertex("Metroville");
        graph1.addVertex("Monstroplolis");
        graph1.addVertex("Narnia");
        graph1.addVertex("Naboo");

        graph1.addEdge("Pandora", "Arendelle");
        graph1.addEdge("Arendelle", "Metroville");
        graph1.addEdge("Arendelle", "Monstroplolis");
        graph1.addEdge("Metroville", "Narnia");
        graph1.addEdge("Metroville", "Naboo");
        graph1.addEdge("Metroville", "Monstroplolis");
        graph1.addEdge("Monstroplolis", "Naboo");
        graph1.addEdge("Narnia", "Naboo");

        System.out.println();
        System.out.println("code challenge 36");
        System.out.println(graph1.bft("Pandora"));
    }
}
