/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void sortTest(){
        int[] arr = {8, 4, 23, 42, 16, 15};
        App app = new App();
        app.sort(arr);
        assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(arr));
    }
}
