/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
 LinkedList<Integer> ll = new LinkedList<>();
        ll.insert(2);
        ll.insert(4);
        ll.insert(5);
        ll.insert(15);
        System.out.println(ll);
        System.out.println(ll.includes(2));
        System.out.println(ll.head.data);
    }


    }

