/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        LinkedList<Integer> linkedList = new LinkedList<>();
        linkedList.insert(1);
        linkedList.insert(2);
        linkedList.insert(3);
        System.out.println(linkedList);
        linkedList.append(8);
        linkedList.append(10);
        System.out.println(linkedList);
        linkedList.insertAfter(2 , 6);
        System.out.println(linkedList);
        linkedList.insertBefore(2 , 5);
        System.out.println(linkedList);
        linkedList.insertBefore(3 , 5);

        System.out.println(linkedList);
//        System.out.println(linkedList.includes(555));
//        System.out.println(linkedList.head.data);
    }
}

