/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class App {
        private static final Stack<Integer> stack = new Stack<>();
        private static final Queue<Integer> queue = new Queue<>();
         private static final stackQueuePseudo<Integer> pseudoQueue = new stackQueuePseudo<>();
          private static final AnimalShelter AnimalSh = new AnimalShelter();


    public static void main(String[] args) {
        System.out.println("Stack");
        stack.push(45);
        stack.push(50);
        stack.push(24);
        System.out.println("Top is ->" +stack.peek());
        System.out.println(" isEmpty: "+ stack.isEmpty());
        System.out.println( stack.pop());
        System.out.println(stack.pop());
        System.out.println( stack.pop());
        System.out.println(" isEmpty: "+ stack.isEmpty());
        System.out.println("Queue");
        queue.enqueue(1);
        queue.enqueue(2);
        queue.enqueue(3);
        System.out.println("is Empty " + queue.isEmpty());
        System.out.println("Front is -> "+ queue.peek());
        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
        System.out.println("Front is "+ queue.peek());
        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
        System.out.println("is Empty: " + queue.isEmpty());
       // code challenge 11
        stack.push(1);
        System.out.println("Code Challenge 11");

        pseudoQueue.enqueue(1);
        pseudoQueue.enqueue(5);
        pseudoQueue.enqueue(15);
        pseudoQueue.enqueue(20);
        pseudoQueue.enqueue(30);
        System.out.println(pseudoQueue);
        System.out.println("dequeue "+pseudoQueue.dequeue());
        System.out.println("dequeue "+pseudoQueue.dequeue());
        System.out.println(pseudoQueue);
        pseudoQueue.enqueue(60);
        System.out.println(pseudoQueue);

        //   Code Challenge 12
        System.out.println("  ");
        System.out.println("  ");
        System.out.println("  ");
        System.out.println("Code Challenge 12");
        System.out.println("   ");
      AnimalSh.enqueue(new Cat("Bondo2"));
        AnimalSh.enqueue(new Cat("Mocha"));
        AnimalSh.enqueue(new Cat("Dongol"));
        AnimalSh.enqueue(new Dog("leo"));
        AnimalSh.enqueue(new Dog("Toby"));
        AnimalSh.enqueue(new Dog("Buddy"));
        System.out.println(AnimalSh);
        AnimalSh.dequeue("Dog");
        System.out.println(AnimalSh);
        AnimalSh.dequeue("Cat");
        AnimalSh.dequeue("Cat");
        System.out.println(AnimalSh);
        AnimalSh.enqueue(new Cat("Bondo2"));
        System.out.println(AnimalSh);
    }
}
