/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class App {
        private static final Stack<Integer> stack = new Stack<>();
        private static final Queue<Integer> queue = new Queue<>();
    public static void main(String[] args) {
        System.out.println("Stack");
        stack.push(45);
        stack.push(50);
        stack.push(24);
        System.out.println("Top is ->" +stack.peek());
        System.out.println(" isEmpty: "+ stack.isEmpty());
        System.out.println( stack.pop());
        System.out.println(stack.pop());
        System.out.println( stack.pop());
        System.out.println(" isEmpty: "+ stack.isEmpty());
        System.out.println("Queue");
        queue.enqueue(1);
        queue.enqueue(2);
        queue.enqueue(3);
        System.out.println("is Empty " + queue.isEmpty());
        System.out.println("Front is -> "+ queue.peek());
        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
        System.out.println("Front is "+ queue.peek());
        System.out.println(queue.dequeue());
        System.out.println(queue.dequeue());
        System.out.println("is Empty: " + queue.isEmpty());
    }
}
