/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.checkerframework.checker.units.qual.A;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void addVertex(){
        Graph graph = new Graph();
        graph.addVertex("Lio");
        graph.addVertex("Mocka");

        assertNotNull(graph.getVertices());
        assertEquals(2,graph.size());
        assertEquals("[Vertex{data='Lio'}, Vertex{data='Mocka'}]",graph.getVertices().toString());
    }

    @Test
    public void printGraph(){
        Graph graph = new Graph();
        graph.addVertex("Lio");
        graph.addVertex("Mocka");
        graph.addEdge("Lio","Mocka");
        assertEquals("Vertex{data='Lio'}[Vertex{data='Mocka'}]Vertex{data='Mocka'}[Vertex{data='Lio'}]",graph.printGraph().toString());
    }
    @Test
    public void getEdge(){
        Graph graph = new Graph();
        graph.addVertex("Lio");
        graph.addVertex("Mocka");
        graph.addEdge("Lio","Mocka");
        assertEquals("[Vertex{data='Mocka'}]",graph.getNeighbors("Lio").toString());
    }
    @Test
    public void removeVertex(){
        Graph graph = new Graph();
        graph.addVertex("Lio");
        graph.addVertex("Mocka");
        graph.addVertex("Bondo2");
        graph.removeVertex("Lio");
        assertEquals(2,graph.size());
    }

    @Test
    void removeEdge(){
        Graph graph = new Graph();
        graph.addVertex("Lio");
        graph.addVertex("Mocka");
        graph.addVertex("Bondo2");
        graph.addEdge("Lio","Mocka");
        graph.addEdge("Lio","Bondo2");
        graph.removeEdge("Lio","Mocka");
        assertEquals("[Vertex{data='Bondo2'}]",graph.getNeighbors("Lio").toString());
    }

    @Test
    void emptyGraph(){
        Graph graph = new Graph();
        assertEquals(0,graph.size());
    }
    @Test
    public void oneVertexAndOneEdge(){
        Graph graph = new Graph();

        graph.addVertex("Lio");
        graph.removeEdge("Lio","Lio");

        assertEquals("Vertex{data='Lio'}[]",graph.printGraph());
    }
    @Test
    public void breathFirst(){
        Graph graph1 = new Graph();

        graph1.addVertex("Pandora");
        graph1.addVertex("Arendelle");
        graph1.addVertex("Metroville");
        graph1.addVertex("Monstroplolis");
        graph1.addVertex("Narnia");
        graph1.addVertex("Naboo");

        graph1.addEdge("Pandora", "Arendelle");
        graph1.addEdge("Arendelle", "Metroville");
        graph1.addEdge("Arendelle", "Monstroplolis");
        graph1.addEdge("Metroville", "Narnia");
        graph1.addEdge("Metroville", "Naboo");
        graph1.addEdge("Metroville", "Monstroplolis");
        graph1.addEdge("Monstroplolis", "Naboo");
        graph1.addEdge("Narnia", "Naboo");

        assertEquals("[Pandora, Arendelle, Metroville, Monstroplolis, Narnia, Naboo]",graph1.bft( "Pandora").toString());
    }
    @Test
    public void oneVertex(){
        Graph graph1 = new Graph();

        graph1.addVertex("Pandora");
        assertEquals("[Pandora]",graph1.bft("Pandora").toString());
    }
    @Test
    void NotEmpty(){
        Graph graph1 = new Graph();
        graph1.addVertex("Pandora");
        assertNotNull("[Pandora]",graph1.bft("Pandora").toString());
    }
    @Test
    public void notAllVertexHaveEdge(){

        Graph graph1 = new Graph();

        graph1.addVertex("Pandora");
        graph1.addVertex("Arendelle");
        graph1.addVertex("Metroville");

        graph1.addEdge("Pandora", "Metroville");

        assertEquals("[Pandora, Metroville]",graph1.bft("Pandora").toString());

    }
    @Test
    void  businessTripTest(){
        Graph graph2 = new Graph();

        graph2.addVertex("Pandora");
        graph2.addVertex("Arendelle");
        graph2.addVertex("Metroville");
        graph2.addVertex("Monstroplolis");
        graph2.addVertex("Narnia");
        graph2.addVertex("Naboo");

        graph2.addEdgeWithWeight("Pandora", "Arendelle", 150);
        graph2.addEdgeWithWeight("Arendelle", "Metroville",99);
        graph2.addEdgeWithWeight("Arendelle", "Monstroplolis",42);
        graph2.addEdgeWithWeight("Metroville", "Narnia",37);
        graph2.addEdgeWithWeight("Metroville", "Naboo",26);
        graph2.addEdgeWithWeight("Metroville", "Monstroplolis",105);
        graph2.addEdgeWithWeight("Monstroplolis", "Naboo",73);
        graph2.addEdgeWithWeight("Narnia", "Naboo",250);

        List<String> cities = new ArrayList<>();
        cities.add("Pandora");
        cities.add("Monstroplolis");
        cities.add("Metroville");
    assertEquals("105",graph2.businessTrip(graph2,cities).toString());
    }
    @Test
    void noTrip(){
        Graph graph2 = new Graph();

        graph2.addVertex("Pandora");
        graph2.addVertex("Arendelle");
        graph2.addVertex("Metroville");
        graph2.addVertex("Monstroplolis");
        graph2.addVertex("Narnia");
        graph2.addVertex("Naboo");

        graph2.addEdgeWithWeight("Pandora", "Arendelle", 150);
        graph2.addEdgeWithWeight("Arendelle", "Metroville",99);
        graph2.addEdgeWithWeight("Arendelle", "Monstroplolis",42);
        graph2.addEdgeWithWeight("Metroville", "Narnia",37);
        graph2.addEdgeWithWeight("Metroville", "Naboo",26);
        graph2.addEdgeWithWeight("Metroville", "Monstroplolis",105);
        graph2.addEdgeWithWeight("Monstroplolis", "Naboo",73);
        graph2.addEdgeWithWeight("Narnia", "Naboo",250);

        List<String> cities = new ArrayList<>();
        cities.add("Pandora");
        cities.add("Naboo");
        assertEquals("0",graph2.businessTrip(graph2,cities).toString());

    }
    @Test
    void TripBetweenTow(){
        Graph graph2 = new Graph();

        graph2.addVertex("Pandora");
        graph2.addVertex("Arendelle");
        graph2.addVertex("Metroville");
        graph2.addVertex("Monstroplolis");
        graph2.addVertex("Narnia");
        graph2.addVertex("Naboo");

        graph2.addEdgeWithWeight("Pandora", "Arendelle", 150);
        graph2.addEdgeWithWeight("Arendelle", "Metroville",99);
        graph2.addEdgeWithWeight("Arendelle", "Monstroplolis",42);
        graph2.addEdgeWithWeight("Metroville", "Narnia",37);
        graph2.addEdgeWithWeight("Metroville", "Naboo",26);
        graph2.addEdgeWithWeight("Metroville", "Monstroplolis",105);
        graph2.addEdgeWithWeight("Monstroplolis", "Naboo",73);
        graph2.addEdgeWithWeight("Narnia", "Naboo",250);
        List<String> cities = new ArrayList<>();
        cities.add("Pandora");
        cities.add("Arendelle");
        cities.add("Naboo");
        assertEquals("150",graph2.businessTrip(graph2,cities).toString());


    }
    @Test
    void depthFirst(){
        Graph graph38 = new Graph();

        graph38.addVertex("A");
        graph38.addVertex("B");
        graph38.addVertex("C");
        graph38.addVertex("D");
        graph38.addVertex("E");
        graph38.addVertex("F");
        graph38.addVertex("G");
        graph38.addVertex("H");

        graph38.addEdge("A", "D");
        graph38.addEdge("A", "B");
        graph38.addEdge("B", "D");
        graph38.addEdge("B", "C");
        graph38.addEdge("C", "G");
        graph38.addEdge("D", "F");
        graph38.addEdge("D", "H");
        graph38.addEdge("D", "E");
        graph38.addEdge("F", "H");
        assertEquals("[A, B, C, G, D, E, H, F]",graph38.dft("A").toString());
    }

    @Test
    void noEdge(){
        Graph graph38 = new Graph();

        graph38.addVertex("A");
        graph38.addVertex("B");
        graph38.addVertex("C");
        graph38.addVertex("D");
        graph38.addEdge("A", "D");
        graph38.addEdge("A", "B");
        graph38.addEdge("B", "D");
        assertEquals("[A, B, D]",graph38.dft("A").toString());
    }
    @Test
    void oneVertexTest(){
        Graph graph38 = new Graph();
        graph38.addVertex("A");
        assertEquals("[A]",graph38.dft("A").toString());
    }
}
